#--- load libraries (all environments)

require 'uuidtools'
require 'digest/sha2'
require 'pdf/writer'
require 'pdf/simpletable'
require 'module_ext'
require 'string_ext'
require 'date_ext'
require 'array_ext'
require 'enumerable_ext'
require 'active_record_ext'
require 'will_paginate_ext'
require 'hash_ext'
require 'association_proxy_ext'
require 'numeric_ext'
require 'money_ext'
require 'active_scaffold_ext'
require 'payment_ext'
require 'bogus_ext'
require 'order_ext'
require 'invoice_ext'
require 'invoice_pdf_ext'
require 'acts_as_state_machine_ext'
require 'credit_card_ext'
require 'flag_ext'
require 'globalize_ext'
require 'record_identification_helper_ext'
require 'field_errors'
require 'bluecloth'
require 'action_view_base_ext'
require 'action_view_helpers_ext'
require 'address_ext'
require 'tag_ext'
# require 'action_mailer_ext'
